### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by kkbalu** [avatsaev/angular-contacts-app-example#22]
http://angular-contacts-ngrx.surge.sh/contacts 
not working. can you check the api

**Comment by avatsaev** [comment]
thanks for letting me know, i'll look into this asap

**Comment by pktippa** [comment]
I think there is something broken,  getting error message "Cannot read property 'message' of undefined"


![image](https://user-images.githubusercontent.com/7558577/47282554-5a1b9780-d5fd-11e8-8746-fc0aaf5be89e.png)


The issue is because of angular app is not able to connect to the WebSocket, could you please add the documentation for configuring and running the WebSocket.?

And the error object handling is not proper in the `contacts-effects.ts`

```ts
alert(err['error']['error']['message']);
```

`err['error']['error']` is  undefined, so cannot read 'message' from undefined.

need to change to `err.message`

**Comment by avatsaev** [comment]
I have a cheap server running the api, and when the hard drive becomes full, the system downs the docker containers, I need to migrate API to another server

**Comment by pktippa** [comment]
may be deploy to a heroku app? free dyno ?

**Comment by avatsaev** [comment]
Demo redeployed to a new server, fully functional again: http://angular-contacts-ngrx.surge.sh
